#!/bin/sh

# Mounting a temporary procfs otherwise the mount process might not work
mount -t proc proc /proc

mkdir -p /mnt/xorg
mkdir -p /mnt/opt/X11/base/rootfs
mkdir -p /mnt/opt/X11/extensions/merged
mkdir -p /mnt/opt/X11/rootfs/write
mkdir -p /mnt/opt/X11/rootfs/work
mkdir -p /mnt/opt/X11/merged

# Mounting X11 rootfs read-only with squashfuse
busybox chroot /mnt "/bin/squashfuse" "/opt/X11/base/xorg.isa" "/opt/X11/base/rootfs"

# Extensions
# Mounting extensions userstore
mount /mnt/opt/storage/extensions.img /mnt/opt/X11/extensions
# Mounting extensions
for f in /mnt/opt/X11/extensions/*.isa ; do
	FILE=`echo "$f" | cut -d'/' -f3-`
	EXTENSION_FOLDER_RAW=`echo "$f" | cut -d'.' -f1`
	EXTENSION_FOLDER=`echo "$EXTENSION_FOLDER_RAW" | cut -d'/' -f3-`
	EXTENSION_FOLDER="/$EXTENSION_FOLDER"
	busybox chroot /mnt "mkdir" "-p" "$EXTENSION_FOLDER"
	busybox chroot /mnt "/bin/squashfuse" "$FILE" "$EXTENSION_FOLDER"
	UNIONFS_FOLDERS_RAW="$UNIONFS_FOLDERS_RAW$EXTENSION_FOLDER:"
done
UNIONFS_FOLDERS="${UNIONFS_FOLDERS_RAW::-1}"

# Mounting extensions UnionFS-FUSE merge point
busybox chroot /mnt "/usr/local/bin/unionfs" "$UNIONFS_FOLDERS" "/opt/X11/extensions/merged"

# Merging X11 rootfs and extensions filesystem together
busybox chroot /mnt "/usr/local/bin/unionfs" "/opt/X11/base/rootfs:/opt/X11/extensions/merged" "/opt/X11/merged"

# Making the union mount read/write and mounting the final overlay to /xorg
busybox chroot /mnt "/bin/fuse-overlayfs" "-o" "lowerdir=/opt/X11/merged,upperdir=/opt/X11/rootfs/write,workdir=/opt/X11/rootfs/work" "/xorg"

rm /mnt/xorg/var/log -rf
mkdir -p /mnt/xorg/var/log

umount /proc -l -f

mount -t devtmpfs devtmpfs /mnt/xorg/dev
mkdir -p /mnt/xorg/dev/shm
mkdir -p /mnt/xorg/dev/pts
mount -t tmpfs tmpfs /mnt/xorg/tmp
mount -t tmpfs tmpfs /mnt/xorg/run
mount -t tmpfs tmpfs /mnt/xorg/dev/shm
mount -t sysfs sysfs /mnt/xorg/sys
mount -t proc proc /mnt/xorg/proc
mount -t devpts devpts /mnt/xorg/dev/pts
touch /mnt/etc/resolv.conf
touch /mnt/xorg/etc/resolv.conf
mount --bind /mnt/etc/resolv.conf /mnt/xorg/etc/resolv.conf

# Launching X
busybox chroot /mnt/xorg "X" "-dpi" "175" &

sleep 5
